import Head from 'next/head';
import { Buy, AR, QR } from '../components';
import Image from 'next/image';
import Link from 'next/link';

const PRODUCT = {
	brand: 'Bacca Bucci',
	name: "Bacca Bucci Men's OffBeat Mid-Top Urban Streetwear Sneakers Socks Shoes | Chunky outsole",
	price: 'Rs. 1,999.00',
	mrp: 'Rs. 4,999.00',
	discount: '60% off',
	image: '/images/shoe.svg',
	link: 'https://www.amazon.in/Bacca-Bucci-OffBeat-Urban-Streetwear/dp/B08JZQZQZK/ref=sr_1_1?dchild=1&keywords=Bacca+Bucci+Men%27s+OffBeat+Mid-Top+Urban+Streetwear+Sneakers+Socks+Shoes+%7C+Chunky+outsole&qid=1619620003&sr=8-1',
};

export default function Home() {
	return (
		<>
			<Head>
				<title>Shop @Rjwada</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className=" select-text overflow-x-hidden">
				<div className="w-full relative md:w-8/12 xl:w-7/12 mx-auto flex flex-col justify-center items-center min-h-screen overflow-x-hidden border border-green-500">
					<div className="absolute md:fixed top-1 px-3 md:px-5 lg:px-8 py-2 w-full flex justify-between items-center">
						<Image src="/images/back-arrow.svg" alt="Back" width={33} height={33} className="" />

						<Image src="/images/brand-logo.svg" alt="Brand Logo" width={150} height={44} className="sm:hidden" />

						<Link href="/qr">
							<Image src="/images/share.svg" alt="Share" width={33} height={33} className="bg-black p-1 rounded-md" />
						</Link>
					</div>

					<div className="hidden sm:flex w-full min-h-fit absolute top-14 p-1 justify-center">
						<button className="relative left-3 w-52 py-2 px-8 mx-1 text-black rounded-full bg-orange-400 hover:bg-orange-500 font-semibold ">
							360 View
						</button>

						<button className="relative right-3 w-52 py-2 px-8 mx-1 text-white font-semibold rounded-full bg-black hover:bg-gray-900">
							View in your room
						</button>
					</div>

					<AR product={PRODUCT} />

					<Buy product={PRODUCT} />
				</div>
			</main>
		</>
	);
}
